name: Deploy HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy
      uses: SyedJunnu/Sample-project-githubactions
      with:
        branch: main
        folder: /Sample-project-githubactions/frontend/index.html/
