name: Deploy HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: SyedJunnu/github-pages-deploy-action@3.7.1
      with:
        branch: gh-pages
        folder: /Sample-project-githubactions/frontend/index.html/
